### ISSUE TITLE
Integrace Wattrouter ECO

### ISSUE THREAD

**Issue by pfemir** [yardee/ha-wattrouter#10]
Dobrý den, existuje nějaká možnost jak integrovat Wattrouter ECO?

**Comment by yardee** [comment]
Dobrý den, podle mě, protože nemá ethernet

**Comment by pfemir** [comment]
Vím že nemá, ale třeba přes nějaký převodník USB-LAN by nebyla možnost ?

**Comment by yardee** [comment]
Nevím o tom, že by to šlo, celkem o tom pochybuji. Ale je to spíš otázka na výrobce SOLAR controls

**Comment by xhyrom** [comment]
Nešlo by to nejak spraviť cez SC-Gateway? "Přes bezdrátovou architekturu tvořenou koordinátorem sítě SC-Gateway. To je možné, jen pokud je do 
přístroje vložen modul SC-Gateway nebo SC-Router. Nelze tedy použít pro WATTrouter M a Heating 
Control."

**Comment by yardee** [comment]
Možné to je, ale nemám jak vyzkoušet

**Comment by xhyrom** [comment]
Jasné, chápem. Ďakujem aj tak za odpoveď :D
