### ISSUE TITLE
ANDI 1 as a binary sensor

### ISSUE THREAD

**Issue by kyselyna** [yardee/ha-wattrouter#11]
ANDI 1 as a binary sensor

Good day,

is it possible to change the input ANDI 1 to a binary sensor 1/0? I need to read the status from this sensor, but even if I have changed it to a binary sensor in the wattrouter, it still looks like energy in the integration

Thank you

**Comment by yardee** [comment]
Hello, I have added new andi sensors, power and binary, can you please try it? I am not using these inputs.

**Comment by kyselyna** [comment]
Hello,

thank you very much for the modification, it works now, I need a binary sensor to modify the export control of the inverter when the distribution network requires 0%

thanks again
