### ISSUE TITLE
Nekompatibilita s FW 2.3

### ISSUE THREAD

**Issue by froxic** [yardee/ha-wattrouter#16]
Zdravim,

Po updatu FW WR na posledni verzi 2.3 prestala integrace kompletne chodit. Nejaky napad? 

Zkousel jsem znovu nacist doplnek, restart HA a nic nepomuze. 

Ve WR logu je toto porad dokola:
30.01.24 15:17:47: [Warning] SOLAR controls protocol says: Protocol error: Error while reading data from device LAN (IP:192.168.88.200,port:50000)!

Nejnovější verze (leden 2024):
Přidáno: Indikátor aktuálního výkonového ofsetu (panel Měřené veličiny).
Přidáno: Indikátor aktuální spotové ceny elektřiny (panel Ostatní stavy).
Přidáno: Vzdálené zdroje měřeného napětí (RVx) lze použít v položkách Napětí pro výpočet u vstupů IL a ANDI (karta Nastavení vstupů).
Přidáno: Vizuální indikátory aktivity časového plánu (karta Časové plány).
Přidáno: Konfigurovatelné časové ofsety pro režimy východu a západu slunce (karta Časové plány).
Přidáno: Podmínky pro spínání podle spotové ceny elektřiny v časových plánech (karta Časové plány).
Přidáno: Konfigurovatelná teplotní hystereze pro teplotní podmínky v časových plánech (karta Další nastavení).
Přidáno: Volba „Řadit výstupy podle fáze a priority“ (karta Další nastavení).
Přidáno: S-CONNECT: Implementovaný protokol verze 2 - nové typy zařízení, ruční párování stanic atd. (karta S-Connect).
Přidáno: S-CONNECT: Integrace s Tasmota a Shelly HTTP API - podpora pro WIFI zásuvky s firmwarem Tasmota a Shelly (karta S-Connect).
Přidáno: S-CONNECT: V tabulce mapování zařízení byla přidána vizuální indikace dostupných zařízení pro každý typ zařízení (karta S-Connect).
Přidáno: Vzdálené binární vstupy RI do online grafu (karta Statistiky).
Přidáno: MODBUS: Další vstupně/výstupní registry pro pokročilou vzdálenou konfiguraci (prioritní výkonový ofset, spotová cena elektřiny).
Přidáno: Typ požadavku OPTIONS do HTTP serveru zařízení.
Přidáno: Hlavičky CORS pro umožnění požadavků HTTP z cizího zdroje (zejména pro potřeby ladění mobilních aplikací).
Přidáno: Exponenciální filtr i pro digitální teplotní senzory (D/Q vstupy).
Přidáno: Podepisování a notarizace aplikace WATTconfig Mx pro MAC (aby vyhověla požadavkům funkce macOS Gatekeeper).
Upraveno: Výrazné zrychlení zápisu konfigurace přes WATTconfig Mx.
Opraveno: Nepřesnost teplot snímaných analogovými teplotními senzory (NTC, PT1000) - filtrování vstupních hodnot bylo částečně nefunkční.
Opraveno: Zobrazení neplatných teplotních hodnot (nyní se zobrazují jako X.X).
Opraveno: Chybějící popisky vstupů RP a RT v rozbalovacích polích Řada X (karta Online graf).
Opraveno: Problémy s vertikálním měřítkem grafů v reálném čase (karta Online graf).
Opraveno: S-CONNECT: Typy vzdálených výstupů RO zůstaly po vypnutí a opětovném zapnutí S-CONNECT neplatné.
Opraveno: S-CONNECT: Nebylo možné mapovat jedno vstupní zdrojové zařízení na různá cílová zařízení (např. V1-RV1, V1-M1).
Opraveno: S-CONNECT: Bylo možné mapovat dvě nebo více zdrojových zařízení na stejné cílové zařízení (např. V1-RV1, M1-RV1).

**Comment by yardee** [comment]
Zdravím, budu muset udělat taky upgrade a upravit integraci. Nedělají ty změny v API úplně kompatibilně, není to poprvé.

**Comment by yardee** [comment]
Dobrý večer, zamergoval jsem fix. Prosím zkuste

**Comment by froxic** [comment]
Dobrý večer, vypadá to že fix funguje!

Ještě zítra důkladně otestuji.

út 30. 1. 2024 v 18:39 odesílatel Michal Baše ***@***.***>
napsal:

**Comment by froxic** [comment]
Tak za mě je ten fix poměrně funkční. Jenom se vrátily krátké výpadky - je to patrné např. u zobrazení NT, úplně to nevadí, ale děje to se párkát za den, přijde mi jak kdyby přímo ten Wattrouter byl místy přetížený a neodpovídal. Síť mám v pořádku. Nedalo by se nastavit jak často se integrace dotazuje WR? Pro můj use case je naprosto dostatečné např co 10s.

Last login: Wed Jan 31 13:39:34 2024 from 192.168.88.107
❯ netstat -na | grep 192.168.88.200:80 | wc -l
180

Většina spojení je TIME_WAIT
tcp        0      0 192.168.88.123:54492    192.168.88.200:80       TIME_WAIT

Pokud jde o počty spojení, tak se to takto chovalo i předtím.

<img width="585" alt="image" src="https://github.com/yardee/ha-wattrouter/assets/15383943/923a466f-ae0e-4660-81bf-299201e27303">

**Comment by yardee** [comment]
Můžu to přidat do konfigu

**Comment by yardee** [comment]
Přidal jsem nastavení update intervalu [v0.4.0](https://github.com/yardee/ha-wattrouter/releases/tag/v0.4.0)

**Comment by froxic** [comment]
Díky. Při změně z 1 na 5 s to vypadá lépe. Dám pak vědět, jestli to
přestalo vypadávat.

❯ netstat -na | grep 192.168.88.200:80 | wc -l
35

Dám pak vědět, jestli

pá 2. 2. 2024 v 13:20 odesílatel Michal Baše ***@***.***>
napsal:

**Comment by froxic** [comment]
Tak můžu potvrdit, že po změně frekvence poolingu na 5s, už nemám problem s nedostupností entit. Vše funguje jak má. Díky. Stejně tak jsem nenarazil na další problémy, co se týče nekompatibility.
